In [1]:
import numpy as np

In [2]:
matrix1 = np.array([[2,1], [1, 3]])

In [4]:
np.linalg.det(matrix1)

5.000000000000001

In [5]:
np.linalg.inv(matrix1)

array([[ 0.6, -0.2],
       [-0.2,  0.4]])

In [13]:
# Matrizen erstellen
matrix1 = np.array([[1,2],[3, 4]])
matrix2 = np.array([[5,6], [7,8]])

# Matrixmultiplikation
product = np.matmul(matrix1,matrix2)

In [14]:
product

array([[19, 22],
       [43, 50]])

In [15]:
# Matrix erstellen
matrix = np.array([[1 , 2], [3, 4]])

# Determinante berechnen
determinant = np.linalg.det(matrix)

# Inverse Matrix berechnen
inverse_matrix = np.linalg.inv(matrix)

In [16]:
determinant

-2.0000000000000004

In [17]:
inverse_matrix

array([[-2. ,  1. ],
       [ 1.5, -0.5]])